### ISSUE TITLE
✨Update DHCP service to enable option 234

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [ministryofjustice/staff-device-dns-dhcp-infrastructure#193]
### User Story

As an EUC service
I need all devices connected to a defined FITS site in the DHCP service to have DHCP Option 234 defined with a generic GUID per site 
So that the EUC service can provide delivery optimisation configuration and reduce the bandwidth on the WAN

### Value / Purpose

This change enables the MoJ OFFICIAL EUC devices to better share application and Windows Update payloads across the local site network without going out to the WAN and Internet.

### Useful Contacts

Matt White, Chandra Singh, Charlie Coverdale

### Additional Information

Historical SPIKE carried out by Cloud Ops - https://dsdmoj.atlassian.net/browse/PTTP-8933
PTTP DAA team backlog item to reduce load - https://dsdmoj.atlassian.net/browse/PTTP-8931

### Definition of Done

- [ ] DHCP config generation has the ability to define and manage DHCP option 234
- [ ] DHCP option 234 is defined once for a FITS site and cascades down to all subnets linked to that site
- [ ] DHCP option 234 is unique for each FITS site and does not overlap (configuration should validate this on changes)
- [ ] DHCP option 234 is defined automatically when a new site is created
- [ ] DHCP option 234 is generated for all existing FITS sites in the service.
- [ ] Value of DHCP option 234 is shown in the admin UI so that users of the DHCP admin UI can map the relationship between FITS site and DHCP option
